export const data = {
    products: [
        {
            title: 'Sweater Gucci',
            description: 'Sweater azul y amarillo especial para el otoño.',
            estado: 10,
            talle: 'M',
            alto: '60cm',
            ancho: '30cm',
            stock: 1,
            price: 5000,
            category: 'Sweater',
            category_id: '1',
            images: ['https://res.cloudinary.com/dbzwohjic/image/upload/v1635723468/BOURNE/gucci_lx7qjm.png', 'https://cdn.childrensalon.com/media/catalog/product/cache/0/image/1000x1000/9df78eab33525d08d6e5fb8d27136e95/g/u/gucci-blue-yellow-wool-sweater-356202-75be018c0b54d0c4b1e00899d6f447b77788e76e.jpg'],
            id: 0,
        },
        {
            title: 'Remera Tommy Hilfiger',
            description: 'Remera Tommy Hilfiger de excelente calidad.',
            estado: 8,
            talle: 'S',
            alto: '60cm',
            ancho: '30cm',
            stock: 3,
            price: 5000,
            category: 'Remera',
            category_id: '0',
            images: ['https://res.cloudinary.com/dbzwohjic/image/upload/v1635723954/BOURNE/tommy_l49ay0.png', 'https://res.cloudinary.com/dbzwohjic/image/upload/v1635724346/BOURNE/tommy2_wpkaht.png'],
            id: 1,
        },
        {
            title: 'Camisa John L. Cook',
            description: 'Camisa floreada John L. Cook. Excelente estado.',
            estado: 10,
            talle: 'XL',
            alto: '70cm',
            ancho: '50cm',
            stock: 2,
            price: 4000,
            category: 'Camisa',
            category_id: '2',
            images: ['https://res.cloudinary.com/dbzwohjic/image/upload/v1635727894/BOURNE/johnlcook_g2fqs9.png', 'https://d3ugyf2ht6aenh.cloudfront.net/stores/001/129/623/products/_dsc56071-35802e27379b9dc9e916325214433597-1024-1024.jpg'],
            id: 2,
        },
        {
            title: 'Pantalon Givenchy',
            description: 'Pantalón negro y blanco de excelente cálidad y estado.',
            estado: 10,
            talle: 'XL',
            alto: '70cm',
            ancho: '50cm',
            stock: 4,
            price: 4300,
            category: 'Pantalon',
            category_id: '3',
            images: ['https://res.cloudinary.com/dbzwohjic/image/upload/v1635728905/BOURNE/givenchy_rypoo9.png'],
            id: 3,
        }
    ]
}